# Generated by Django 5.0.6 on 2024-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='transection_type',
            field=models.IntegerField(choices=[('1', 'DEPOSITE'), ('WITHDRAW', 'WITHDRAW'), ('LOAN', 'LOAN'), ('LOAN_PAID', 'LOAN PAID')]),
        ),
    ]
