# Generated by Django 5.0.6 on 2024-06-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transections', '0002_alter_transection_transection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='transection_type',
            field=models.IntegerField(choices=[(1, 'DEPOSITE'), (2, 'WITHDRAW'), (3, 'LOAN'), (4, 'LOAN PAID'), (5, 'TRANSFER_MONEY')]),
        ),
    ]
