DEPOSITE=1
WITHDRAW=2
LOAN=3
LOAN_PAID=4
TRANSFER_MONEY=5
TRSANSECTION_TYPE={
    DEPOSITE:'DEPOSITE',
    WITHDRAW:'WITHDRAW',
    LOAN:'LOAN',
    LOAN_PAID:'LOAN PAID',
    TRANSFER_MONEY:'TRANSFER_MONEY'
}
# DEPOSIT = 1
# WITHDRAW = 2
# LOAN = 3
# LOAN_PAID = 4
# TRANSFER_MONEY = 5

# TRANSACTION_TYPE = {
#     DEPOSIT: 'DEPOSIT',
#     WITHDRAW: 'WITHDRAW',
#     LOAN: 'LOAN',
#     LOAN_PAID: 'LOAN PAID',
#     TRANSFER_MONEY: 'TRANSFER_MONEY'
# }
